4package:
    name: enginemeta
    version: 1.0.15
requirements:
    run:
        - requests ==2.13.0
        - concurrentloghandler ==0.9.1
        - pandas ==0.19.2
        - ion-functions ==2.4.2
        - numexpr ==2.6.2
        - netcdf4 ==1.2.4
        - nomkl
        - simplejson ==3.10.0
        - python ==2.7.15
        - msgpack-python ==0.4.8
        - cachetools ==2.0.0
        - flask ==0.12
        - mi-instrument ==0.8.0
        - geoalchemy2 ==0.4.0
        - xarray ==0.9.2
        - ntplib ==0.3.3
        - gunicorn ==19.7.0
        - numpy ==1.12
        - scipy ==0.19.0
        - sqlalchemy ==1.1.5
        - ooi-data ==0.0.5
        - pygsw ==0.0.11
        - futures ==2.2.0
        - cassandra-driver ==3.9.0
about:
    summary: Ingest and stream engine metapackage
