package:
    name: stream_engine
    version: 1.19.2

source:
    git_url: https://github.com/oceanobservatories/stream_engine
    git_rev: v1.19.2

requirements:
    run:

about:
    summary: Stream engine
