package:
    name: stream_engine
    version: 1.18.0

source:
    git_url: https://github.com/oceanobservatories/stream_engine
    git_rev: v1.18.0

requirements:
    run:

about:
    summary: Stream engine
