package:
    name: ingest_engine
    version: 1.4.0

source:
    git_url: ssh://uframe-cm.ooi.rutgers.edu:29418/ingest_engine
    git_rev: v1.4.0

requirements:
    run:

about:
    summary: Ingest engine
