package:
    name: ingest_engine
    version: 1.4.5

source:
    git_url: ssh://pmena@ooi-pmo-prd02.whoi.edu:29418/ingest_engine
    git_rev: v1.4.5

requirements:
    run:

about:
    summary: Ingest engine
