package:
    name: ingest_engine
    version: 1.4.2

source:
    git_url: ssh://uframe-cm.ooi.rutgers.edu:29418/ingest_engine
    git_rev: v1.4.2

requirements:
    run:

about:
    summary: Ingest engine
